import { getTherapySession } from './api.js';

// ─── Project placeholders — replace before launch ─────────────────────────────
const X_HANDLE = 'soltherapyctc';          // e.g. 'SolTherapy' → x.com/SolTherapy
const CONTRACT_ADDRESS = 'TBA';          // paste CA here once deployed

const app = document.getElementById('app');
let currentLoss = '';
let currentTherapy = null;
let currentWalletInfo = '';

function renderHero() {
  app.innerHTML = `
    <header>
      <div class="logo">
        <img src="logo.png" class="logo-img" alt="SolTherapy Logo" />
        SolTherapy
      </div>
      <div class="header-links">
        <a class="header-link" href="https://x.com/${X_HANDLE}" target="_blank" rel="noopener">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.743l7.735-8.835L1.254 2.25H8.08l4.253 5.622zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
          @${X_HANDLE}
        </a>
      </div>
    </header>

    <section class="hero">
      <div class="hero-badge">
        <div class="hero-badge-dot"></div>
        Accepting New Patients
      </div>

      <h1>
        <span class="line-1">Confess Your</span>
        <span class="line-2">Bags.</span>
      </h1>
      <p class="hero-sub">
        You didn't lose money. You just allocated capital into a very competitive
        experimental defi ecosystem at an inopportune moment.
      </p>

      <div class="input-card">
        <div class="input-label">Confession</div>
        <form id="form">
          <div class="input-wrap">
            <div class="input-prefix">$</div>
            <input
              id="loss"
              type="text"
              placeholder="Amount lost, or paste Solana wallet…"
              autocomplete="off"
            />
          </div>
          <div class="divider-row">or paste wallet to auto-detect PnL</div>
          <button class="btn-primary" type="submit">Start Session →</button>
        </form>
        <p class="input-hint">Free. Confidential. Mildly condescending.</p>
      </div>

      <div class="token-info-bar">
        <a class="token-info-item" href="https://x.com/${X_HANDLE}" target="_blank" rel="noopener">
          <span class="token-info-label">
            <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.743l7.735-8.835L1.254 2.25H8.08l4.253 5.622zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
            Follow
          </span>
          <span class="token-info-value">@${X_HANDLE}</span>
        </a>
        <div class="token-info-divider"></div>
        <div class="token-info-item clickable" id="ca-copy-trigger">
          <span class="token-info-label">CA</span>
          <span class="token-info-value mono" id="ca-text">${CONTRACT_ADDRESS === 'TBA' ? 'TBA — Coming Soon' : CONTRACT_ADDRESS}</span>
        </div>
      </div>
    </section>

    <section class="testimonials">
      <div class="testimonials-label">Recent Patients</div>
      <div class="testimonial-grid">
        <div class="testimonial-card">
          <div class="t-handle">@degen.sol</div>
          <div class="t-text">"I've lost more to rug pulls than therapy normally costs. This felt fair."</div>
        </div>
        <div class="testimonial-card">
          <div class="t-handle">@wagmi_always</div>
          <div class="t-text">"Diagnosed with Chronic Bottom Ticker Syndrome. Accurate. Haunting."</div>
        </div>
        <div class="testimonial-card">
          <div class="t-handle">@flippening_guy</div>
          <div class="t-text">"Posted the certificate. 2,400 likes. Made back half my losses in attention."</div>
        </div>
      </div>
    </section>

    <section class="charity-section">
      <div class="charity-content">
        <div class="charity-icon">❤️‍🩹</div>
        <h2>Our Commitment to Recovery</h2>
        <p>A portion of all trading fees generated by the SolTherapy token will be directly donated to <a href="https://gamblersanonymous.org/" target="_blank" rel="noopener">Gamblers Anonymous</a>. Because while crypto trauma is a meme, gambling addiction is not.</p>
      </div>
    </section>

    <footer class="app-footer">
      <p>Not real financial or medical advice. Please touch grass.</p>
      <p class="hotline">Crisis Lifeline: Dial The Suicide And Crisis Lifeline via <strong>988</strong></p>
    </footer>
  `;

  // CA copy by clicking the whole item
  const caTrigger = document.getElementById('ca-copy-trigger');
  const caText = document.getElementById('ca-text');
  if (caTrigger) {
    caTrigger.addEventListener('click', () => {
      const textToCopy = CONTRACT_ADDRESS === 'TBA' ? 'TBA' : CONTRACT_ADDRESS;
      navigator.clipboard.writeText(textToCopy).then(() => {
        const originalText = CONTRACT_ADDRESS === 'TBA' ? 'TBA — Coming Soon' : CONTRACT_ADDRESS;
        caText.textContent = 'Copied!';
        caText.style.color = 'var(--green)';
        setTimeout(() => {
          caText.textContent = originalText;
          caText.style.color = '';
        }, 1500);
      });
    });
  }

  document.getElementById('form').addEventListener('submit', async (e) => {
    e.preventDefault();
    const raw = document.getElementById('loss').value.trim();
    if (!raw) return;

    const isSolAddr = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(raw);

    if (isSolAddr) {
      renderLoading('Pulling wallet history from the chain…', 'Please allow a moment for your mistakes to load.');
      try {
        const isLocal = location.hostname === 'localhost' || location.hostname === '127.0.0.1';
        if (isLocal) {
          await new Promise(r => setTimeout(r, 1800));
          currentLoss = '-$14,200';
          currentWalletInfo = '7d realized PnL: -$14,200, win rate: 23%, 42 trades';
        } else {
          const wRes = await fetch(`/api/wallet?address=${encodeURIComponent(raw)}`);
          const wData = await wRes.json();
          if (!wRes.ok || !wData.lossString) {
            renderWalletError();
            return;
          }
          currentLoss = wData.lossString;
          currentWalletInfo = wData.summary || '';
        }
      } catch (err) {
        renderWalletError();
        return;
      }
    } else {
      const digits = raw.replace(/[^0-9.]/g, '');
      currentLoss = digits ? '$' + parseFloat(digits).toLocaleString() : raw;
      currentWalletInfo = '';
      renderLoading('Reviewing your financial decisions…', 'Please allow a moment for judgment to fully form.');
    }

    getTherapySession(currentLoss, currentWalletInfo).then(data => {
      currentTherapy = data;
      currentLoss = data.loss || currentLoss;
      setTimeout(renderSession, 400);
    });
  });
}

function renderLoading(title = 'Reviewing your financial decisions…', sub = 'Please allow a moment for judgment to fully form.') {
  app.innerHTML = `
    <div class="loading-view">
      <div class="spinner-ring"></div>
      <div>
        <p class="loading-text">${title}</p>
        <p class="loading-sub">${sub}</p>
      </div>
    </div>
  `;
}

function renderWalletError() {
  app.innerHTML = `
    <div class="loading-view">
      <div style="font-size:2rem">🔍</div>
      <div>
        <p class="loading-text">Wallet data unavailable</p>
        <p class="loading-sub">GMGN couldn't pull data for this address.<br/>Try entering your loss amount manually.</p>
      </div>
      <button class="btn-primary" id="back-btn" style="max-width:280px;margin-top:1rem;">← Try Again</button>
    </div>
  `;
  document.getElementById('back-btn').addEventListener('click', () => {
    currentLoss = '';
    currentWalletInfo = '';
    renderHero();
  });
}

function renderSession() {
  const { paragraphs } = currentTherapy;
  const paras = paragraphs.map(p => `<p class="session-para">${p}</p>`).join('');

  app.innerHTML = `
    <div class="session-view">
      <div class="session-header">
        <div class="session-avatar">🩺</div>
        <div>
          <div class="session-doctor">Dr. Claude AI</div>
          <div class="session-creds">Board Certified · Crypto Trauma Specialist</div>
        </div>
      </div>
      <div class="session-body">
        ${paras}
        <div class="session-actions">
          <button class="btn-cert" id="cert-btn">
            View Diagnosis Certificate ↓
          </button>
        </div>
      </div>
    </div>
  `;

  document.getElementById('cert-btn').addEventListener('click', renderCertificate);
}

function renderCertificate() {
  const { diagnosis } = currentTherapy;
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  app.innerHTML = `
    <div class="cert-view">
      <h2>Your Official Diagnosis</h2>

      <div id="cert-card">
        <div class="cert-top-bar"></div>
        <div class="cert-inner">
          <img src="logo.png" class="cert-watermark" alt="" />

          <div class="cert-top-row">
            <div class="cert-issuer">
              Issued by
              <strong>SolTherapy Trauma Center</strong>
            </div>
            <img src="logo.png" class="cert-seal" alt="Seal" />
          </div>

          <p class="cert-statement">This certifies that the bearer has been clinically diagnosed with</p>
          <div class="cert-name">${diagnosis}</div>

          <div class="cert-meta-row">
            <div class="cert-meta-item">
              <div class="cert-meta-label">Realized Loss</div>
              <div class="cert-meta-value loss">${currentLoss}</div>
            </div>
            <div class="cert-meta-item">
              <div class="cert-meta-label">Prognosis</div>
              <div class="cert-meta-value diag">Cautiously Hopeful</div>
            </div>
          </div>

          <div class="cert-footer-bar">
            <div class="cert-date-block">Date of Session<br/>${dateStr}</div>
            <div class="cert-sig-block">
              <div class="cert-sig">Dr. Claude AI</div>
              <div class="cert-sig-title">Attending Therapist, SolTherapy®</div>
            </div>
          </div>
        </div>
      </div>

      <div class="cert-btns">
        <button class="btn-icon" id="save-btn">
          ↓ &nbsp;Save as PNG
        </button>
        <button class="btn-icon twitter" id="tweet-btn">
          𝕏 &nbsp;Share on X
        </button>
        <button class="btn-new" id="new-btn">New Session</button>
      </div>
    </div>
  `;

  document.getElementById('save-btn').addEventListener('click', async () => {
    try {
      const canvas = await html2canvas(document.getElementById('cert-card'), {
        backgroundColor: '#09090f',
        scale: 2,
        useCORS: true,
      });
      const a = document.createElement('a');
      a.href = canvas.toDataURL('image/png');
      a.download = 'soltherapy-certificate.png';
      a.click();
    } catch (err) {
      alert('Export failed. Try right-clicking and saving the card manually.');
    }
  });

  document.getElementById('tweet-btn').addEventListener('click', async () => {
    const btn = document.getElementById('tweet-btn');
    const originalText = btn.innerHTML;
    btn.innerHTML = '⏳ &nbsp;Preparing...';
    btn.style.opacity = '0.7';
    btn.style.pointerEvents = 'none';

    const { diagnosis } = currentTherapy;
    const rawText = `Just got clinically diagnosed with "${diagnosis}" after losing ${currentLoss} on Solana.\n\nFree therapy at soltherapy.io 🩺 @${X_HANDLE}`;

    try {
      const canvas = await html2canvas(document.getElementById('cert-card'), {
        backgroundColor: '#09090f',
        scale: 2,
        useCORS: true,
      });

      canvas.toBlob(async (blob) => {
        const file = new File([blob], 'soltherapy-certificate.png', { type: 'image/png' });
        
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
          try {
            await navigator.share({
              text: rawText,
              files: [file]
            });
          } catch (err) {
            console.log('Share canceled or failed', err);
          }
        } else {
          // Desktop fallback: Download it and open Twitter intent
          const a = document.createElement('a');
          a.href = canvas.toDataURL('image/png');
          a.download = 'soltherapy-certificate.png';
          a.click();
          
          const text = encodeURIComponent(rawText + '\n\n(Attach your downloaded certificate below!)');
          window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
        }
        
        btn.innerHTML = originalText;
        btn.style.opacity = '1';
        btn.style.pointerEvents = 'auto';
      });
    } catch (err) {
      // Fallback if canvas generation fails
      const text = encodeURIComponent(rawText);
      window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
      
      btn.innerHTML = originalText;
      btn.style.opacity = '1';
      btn.style.pointerEvents = 'auto';
    }
  });

  document.getElementById('new-btn').addEventListener('click', () => {
    currentLoss = '';
    currentTherapy = null;
    currentWalletInfo = '';
    renderHero();
  });
}

renderHero();
